name: Build Privacy Magic Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Clean artifacts folder
        run: rm -rf ./artifacts && mkdir ./artifacts
      - name: Install dependencies
        run: npm install
      - name: Build extension
        run: npm run build
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: privacymagic-${{ github.ref_name }}.zip
          files: ./artifacts/privacymagic.zip
      - name: Upload zip-file artifact
        uses: actions/upload-artifact@v6
        with:
          name: privacymagic-${{ github.ref_name }}.zip
          path: ./artifacts/privacymagic.zip
